### ISSUE TITLE
Built-in Wikipedia search breaks on NM v0.5.0

### ISSUE THREAD

**Issue by PeterJT** [pgaskin/NickelMenu#101]
With a basic config in place attempts to use the Search / Wikipedia function fails; the browser just displays Loading...

```
experimental:menu_main_15505_label:Custom

menu_item :main   :Invert Screen   :nickel_setting :toggle :invert
menu_item :reader :Screen Shots    :nickel_setting :toggle :screenshots
menu_item :library:Invert Screen   :nickel_setting :toggle :invert
menu_item :main   :Screen Shots    :nickel_setting :toggle :screenshots
menu_item :reader :Invert Screen   :nickel_setting :toggle :invert
menu_item :library:Screen Shots    :nickel_setting :toggle :screenshots

menu_item :main   :USB Auto        :nickel_setting :toggle :auto_usb_gadget
menu_item :reader :USB Auto        :nickel_setting :toggle :auto_usb_gadget
menu_item :library:USB Auto        :nickel_setting :toggle :auto_usb_gadget

menu_item :main   :CW - Peter      :nickel_browser :modal:http://192.168.2.91:8083
menu_item :main   :CW - Peter (Ext):nickel_browser :modal:http://xxxx.duckdns.org:8083
```

**Comment by pgaskin** [comment]
A few questions:

1. Do the menu items you added work?
2. Which language is the book?
3. Which language is the device?
4. If possible, can you send the syslog after trying both?

**Comment by pgaskin** [comment]
MR:thread-336577

**Comment by pgaskin** [comment]
I have updated the [release notes](https://github.com/pgaskin/NickelMenu/releases/tag/v0.5.0) for v0.5.0 to mention this issue:

> **Update:** This release has a bug which causes the built-in Wikipedia search to temporarily stop working. See #101 for details. I will release a fix for this soon. If you need the built-in Wikipedia search, you can use v0.4.1 for now. I apologize for any inconvenience this has caused.

**Comment by PeterJT** [comment]
Many thanks for the update.

**Comment by pgaskin** [comment]
I just took a quick look, and I found the issue:

```
"https://word.m.wikipedia.org/wiki/Special:Search?search=en" => "Host word.m.wikipedia.org not found"
```

:facepalm: I mixed up the function parameter order while I did the final refactor...

https://github.com/pgaskin/NickelMenu/blob/0429525e1dfbf4c8ee2128d2fb6140343bf1037b/src/nickelmenu.cc#L568-L576

**Comment by pgaskin** [comment]
Fix released in [v0.5.1](https://github.com/pgaskin/NickelMenu/releases/tag/v0.5.1).

**Comment by pgaskin** [comment]
cc @NiLuJe for the OCPs

**Comment by NiLuJe** [comment]
Way ahead of you ;p.

> Last updated on Sat, 16 Jan 2021 04:51:35 +0100
