### ISSUE TITLE
NickelMenu won't show up

### ISSUE THREAD

**Issue by MilGreat2010** [pgaskin/NickelMenu#115]
On my Kobo Clara HD on firmware 4.30.18838 the NickelMenu won't show up! Can someone help me?

**Comment by pgaskin** [comment]
How did you install NM?

**Comment by MilGreat2010** [comment]
> How did you install NM?

I dragged KoboRoot.tgz to the .kobo folder. it did show the updating and the dont power off screen

**Comment by pgaskin** [comment]
Which OS are you using?

**Comment by MilGreat2010** [comment]
> Which OS are you using?

macOS Monterey 12.0.1 (21A559) and I have the standard M1 MacBook Air.

**Comment by MilGreat2010** [comment]
Im waiting for the new version

**Comment by pgaskin** [comment]
Sorry about the delay, I missed the reply.

How did you install NM? It should be compatible with 18838.

**Comment by MilGreat2010** [comment]
I will try again later today.

**Comment by MilGreat2010** [comment]
It worked! Found out that my MacBook automatically de-zips files, so it came out as KoboRoot.tar, but the .tgz file was there in the trash bin!

**Comment by pgaskin** [comment]
Oh, that. I forgot that macOS does that since I haven't used it in a while. I'm going to have to figure out a way to stop it from doing that.

**Comment by MilGreat2010** [comment]
Maybe..... Just package KoboRoot.tgz in a zip file?
