### ISSUE TITLE
Dark Mode Error (Libra H20) Firm. 4.3

### ISSUE THREAD

**Issue by ZeFish** [pgaskin/NickelMenu#116]
First thanks for the nice hack you have made here!! It does save me from buying another reader to get that small but so fun feature!

### Dark Mode
It seems that on my Libra H20 the Dark Mode doesn't work I get that error. Hopefully it mean something to you :)
![PXL_20211123_173321965 MP](https://user-images.githubusercontent.com/24323/143075898-ff71247f-192c-4ca9-b01a-cbb29bcdb2a5.jpg)
My reader use the software 4.30.18838 (9bbb7fadc79, 10/30/21)

### Invert Mode
Well that one seems to work but I need to reboot the device everytime. I know this is the prior version of "Dark Mode" but for now it get the job done.

Here's my config
`menu_item :reader  :Invert Screen      :nickel_setting     :toggle :invert`
`menu_item :reader  :Dark Mode          :nickel_setting     :toggle :dark_mode`
`menu_item :main  :Invert Screen      :nickel_setting     :toggle :invert`
`menu_item :main  :Dark Mode          :nickel_setting     :toggle :dark_mode`

**Comment by jeff47** [comment]
Same issue - dark_mode doesn't work on the Libra H2O.  As you mentioned, Invert does work but requires a reboot.

To make your workaround a little easier, you can chain together the actions as described here:  https://www.mobileread.com/forums/showthread.php?t=341175.

You can put this in your config:
```menu_item :reader :Invert Screen   :nickel_setting :toggle:invert
    chain_success                  :power          :reboot
```

**Comment by pgaskin** [comment]
That's because I haven't released the dark_mode option yet. I still need to figure out a few things regarding applying the settings instantly.

**Comment by pgaskin** [comment]
fixed in 7c82cc4450c66af003f1a7c9825006b05606477f and 749483b883448c9f4df538f144a5e26f7f244e46
