### ISSUE TITLE
Issue highlighting on 4.31.19086

### ISSUE THREAD

**Issue by DavidNSB** [pgaskin/NickelMenu#119]
After installing the 4.31.19086 firmware, an attempt to hightlight a phrase, a popup "NickelMenu  Could not find the required SelectionMenuView and SelectionMneuController symbols for adding selection menu items (this is a bug)" was displayed.  After clicking OK 3 times, the highlight menu was displayed.

**Comment by pgaskin** [comment]
I will try and release a fix for this tonight.

**Comment by shermp** [comment]
@pgaskin do you want me to take a quick look at this once I've decompiled `libnickel`?

**Comment by pgaskin** [comment]
Yes, if you want to.

**Comment by shermp** [comment]
Ok, will do, just waiting for Ghidra to finish chugging away at this.

**Comment by shermp** [comment]
Looks like `SelectionMenuController::lookupWeb()` is gone.

Looks like it may have been replaced with `SelectionMenuController::lookupGoogle()` and `SelectionMenuController::lookupBaidu()`

**Comment by pgaskin** [comment]
Fixed in [`v0.5.3`](https://github.com/pgaskin/NickelMenu/releases/v0.5.3).
