### ISSUE TITLE
Add option to hide "More" button in main menu

### ISSUE THREAD

**Issue by Colonial-Dev** [pgaskin/NickelMenu#127]
Hey, I just got my first Kobo and I've been loving NickelMenu so far! 

I'm not sure if this is already configurable - it looks like you gave it some thought in #78 - but I was wondering if you could add a way to hide the "More" button from the tab select in the main menu. It's just kind of redundant with NM installed, seeing as you can access everything it contains using `nickel-open`.

Thanks for your time!

**Comment by farfalleflickan** [comment]
Seconded! Maybe merge the two menus somehow?

Anyway, thanks for all your work!

**Comment by Sandros94** [comment]
For me (just got a Libra 2) I would prefer a config that allows me to move the the `NickelMenu` inside the `More` menu.
Since my current config only has items for non-`main` locations.

**Comment by mrleblanc101** [comment]
Same, it feels weird to have 2 hamburger menu at the bottom
