### ISSUE TITLE
Config file being ignored

### ISSUE THREAD

**Issue by bobf32** [pgaskin/NickelMenu#133]
I have created a file called config in the .adds/nm folder with content:

`menu_item :library :Import books       :nickel_misc        :rescan_books_full`

I have rebooted my kobo and still the only option in the Nickel menu is KOreader (which was added by following the instructions [here](https://www.mobileread.com/forums/showpost.php?p=3797096&postcount=2))

I am expecting an additional menu option to allow a book import. 

Am I doing something wrong?

**Comment by NiLuJe** [comment]
`menu_item :library` affects the Library's  `⋮` menu, not the Home's extra NM menu.

**Comment by bobf32** [comment]
Thank you @NiLuJe. I had assumed that all menu options were added to the bottom right menu.

I only feel a bit silly now :)
