### ISSUE TITLE
FeatureRequest: shorter autoshutdown timeout

### ISSUE THREAD

**Issue by formula-spectre** [pgaskin/NickelMenu#147]
as of now the shortest I can make it is one day, which is not how I really like it.
on vanilla kobo I have suspend in 15 minutes, and that I can replicate in nm, and poweroff in 2 hours, which is too little for nm.
is there a way to have that?

**Comment by NiLuJe** [comment]
Also wrong repo ;).

c.f., https://www.mobileread.com/forums/showthread.php?t=356479

**Comment by formula-spectre** [comment]
i'm so sorry! I was pretty sure I was in the koreader repo! my apologies! same goes for the other issue!
