### ISSUE TITLE
standby/screensaver message battery percentage not getting updated?

### ISSUE THREAD

**Issue by formula-spectre** [pgaskin/NickelMenu#148]
settings -> screen -> screensaver -> add message to screensaver[settings] -> screensaver message; if I put %b, which is the battery level, it gets displayed fine in the message when my kobo is in standby, but it does not get updated; say the battery drops by 5%, the message does not get update. is this intentional?

**Comment by pgaskin** [comment]
Um, what? Nickel doesn't have a screensaver message.

@NiLuJe, I think this is [koreader](https://github.com/koreader/koreader/blob/27104ea011da1222e4372ce6118e1829fd1830c9/frontend/ui/elements/screensaver_menu.lua#L40).

**Comment by NiLuJe** [comment]
Yup, wrong repo ;).

Also: the device is alseep, so, no the screen will *not* update. It's a feature, not a bug.

**Comment by formula-spectre** [comment]
sorry again! I thought I was in the koreader repo :/ my apologies
