### ISSUE TITLE
Cannot create `.adds` folder at the root

### ISSUE THREAD

**Issue by gotson** [pgaskin/NickelMenu#168]
Hi,

i am trying to uninstall NickelMenu, and there is no `.adds` folder at the root of the mounted Kobo. I am on a Mac.

When i try to create the empty `.adds` folder, i get an error saying i don't have enough permissions:

<img width="243" alt="image" src="https://github.com/user-attachments/assets/fdd461ad-c2b9-4cca-b0d2-cdc86754ee29">

I get a similar issue when trying from the Terminal:

<img width="269" alt="image" src="https://github.com/user-attachments/assets/7f559115-f4c6-4743-8e3f-2ca07798038a">

Would appreciate any tips on uninstalling.

I am using a Kobo Libra Colour.

**Comment by pgaskin** [comment]
Did you end up figuring it out?

**Comment by gotson** [comment]
i believe it's some policy set by the admin of my macbook which is a corporate device
