### ISSUE TITLE
nickel_setting DeveloperSettings AutoUsbGadget option

### ISSUE THREAD

**Issue by pgaskin** [pgaskin/NickelMenu#76]
As requested on MR:post-4020337.

**Comment by begemot4** [comment]
Hello

Can you add screensaver management? So that you can turn on the book cover or the pictures in the screensaver folder.

Unfortunately, Kobo missed this option in the settings and now have to do everything manually.

**Comment by pgaskin** [comment]
> Can you add screensaver management? So that you can turn on the book cover or the pictures in the screensaver folder.

You need to enable full-screen covers in the "Energy Saving and Privacy" section.
