### ISSUE TITLE
Custom icon for NickelMenu main menu on 4.23.15505

### ISSUE THREAD

**Issue by pgaskin** [pgaskin/NickelMenu#84]
See #78.

**Comment by NiLuJe** [comment]
Random thought: instead of/in the meantime, couldn't we simply re-purpose an existing one? (I was thinking of the Erlenmeyer of the "Beta" settings, or any of the existing gear/tool-like ones).

**Comment by pgaskin** [comment]
> instead of/in the meantime, couldn't we simply re-purpose an existing one

I was actually just thinking something along the same line. I'm considering making an experimental option for now to change the path used for the QPixmap, as that would allow loading it from an arbitrary resource or a file. That allows us to sidestep the decisions for this change for now.

The only thing I'm concerned about is I don't want experimental options to become widely-used and having people complain about breakage/removal/changes later. That's a discussion for #87, though.

**Comment by pgaskin** [comment]
I've decided to go with an experimental option to change the QPixmap path for now.

**Comment by acestronautical** [comment]
I tried setting:
```
experimental:menu_main_15505_icon_active:/images/reading/beta_features_hit.png
experimental:menu_main_15505_icon:/images/reading/beta_features.png
```
but it doesn't seem to be working. Is this supposed to work with the native paths on kobo?
(I have libra 2)

**Comment by pgaskin** [comment]
Try adding another colon before the path and see if it works.
